### ISSUE TITLE
Right facing ribbons

### ISSUE THREAD

**Issue by sschuchlenz** [Localvox/3D-CORNER-RIBBONS#3]
Hi,

I really like your work but for a project of mine I wanted to have ribbons on the opposite side of the box I attached them too and (at least in the version I used) there was no option to do that. If you like have a look at the gist here https://gist.github.com/sschuchlenz/d9b24390fd301eba0e81, I added **.ribbon-right** as a "modifier class" - maybe this is useful to you (didn't really do much testing though, so maybe there is something off ;)

Thanks for your work and effort!

**Comment by Shaz3e** [comment]
+1
